# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rr_openrover_driver_msgs/RawRrOpenroverDriverMedRateData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class RawRrOpenroverDriverMedRateData(genpy.Message):
  _md5sum = "8d1326600b05770e80fedaabbf1fed8a"
  _type = "rr_openrover_driver_msgs/RawRrOpenroverDriverMedRateData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int32 reg_pwr_total_current
int32 reg_motor_fb_rpm_left
int32 reg_motor_fb_rpm_right
int32 reg_flipper_fb_position_pot1
int32 reg_flipper_fb_position_pot2
int32 reg_motor_fb_current_left
int32 reg_motor_fb_current_right
int32 reg_motor_charger_state
int32 reg_power_a_current
int32 reg_power_b_current
int32 reg_motor_flipper_angle
int16 battery_current_a
int16 battery_current_b
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','reg_pwr_total_current','reg_motor_fb_rpm_left','reg_motor_fb_rpm_right','reg_flipper_fb_position_pot1','reg_flipper_fb_position_pot2','reg_motor_fb_current_left','reg_motor_fb_current_right','reg_motor_charger_state','reg_power_a_current','reg_power_b_current','reg_motor_flipper_angle','battery_current_a','battery_current_b']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,reg_pwr_total_current,reg_motor_fb_rpm_left,reg_motor_fb_rpm_right,reg_flipper_fb_position_pot1,reg_flipper_fb_position_pot2,reg_motor_fb_current_left,reg_motor_fb_current_right,reg_motor_charger_state,reg_power_a_current,reg_power_b_current,reg_motor_flipper_angle,battery_current_a,battery_current_b

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RawRrOpenroverDriverMedRateData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.reg_pwr_total_current is None:
        self.reg_pwr_total_current = 0
      if self.reg_motor_fb_rpm_left is None:
        self.reg_motor_fb_rpm_left = 0
      if self.reg_motor_fb_rpm_right is None:
        self.reg_motor_fb_rpm_right = 0
      if self.reg_flipper_fb_position_pot1 is None:
        self.reg_flipper_fb_position_pot1 = 0
      if self.reg_flipper_fb_position_pot2 is None:
        self.reg_flipper_fb_position_pot2 = 0
      if self.reg_motor_fb_current_left is None:
        self.reg_motor_fb_current_left = 0
      if self.reg_motor_fb_current_right is None:
        self.reg_motor_fb_current_right = 0
      if self.reg_motor_charger_state is None:
        self.reg_motor_charger_state = 0
      if self.reg_power_a_current is None:
        self.reg_power_a_current = 0
      if self.reg_power_b_current is None:
        self.reg_power_b_current = 0
      if self.reg_motor_flipper_angle is None:
        self.reg_motor_flipper_angle = 0
      if self.battery_current_a is None:
        self.battery_current_a = 0
      if self.battery_current_b is None:
        self.battery_current_b = 0
    else:
      self.header = std_msgs.msg.Header()
      self.reg_pwr_total_current = 0
      self.reg_motor_fb_rpm_left = 0
      self.reg_motor_fb_rpm_right = 0
      self.reg_flipper_fb_position_pot1 = 0
      self.reg_flipper_fb_position_pot2 = 0
      self.reg_motor_fb_current_left = 0
      self.reg_motor_fb_current_right = 0
      self.reg_motor_charger_state = 0
      self.reg_power_a_current = 0
      self.reg_power_b_current = 0
      self.reg_motor_flipper_angle = 0
      self.battery_current_a = 0
      self.battery_current_b = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11i2h().pack(_x.reg_pwr_total_current, _x.reg_motor_fb_rpm_left, _x.reg_motor_fb_rpm_right, _x.reg_flipper_fb_position_pot1, _x.reg_flipper_fb_position_pot2, _x.reg_motor_fb_current_left, _x.reg_motor_fb_current_right, _x.reg_motor_charger_state, _x.reg_power_a_current, _x.reg_power_b_current, _x.reg_motor_flipper_angle, _x.battery_current_a, _x.battery_current_b))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.reg_pwr_total_current, _x.reg_motor_fb_rpm_left, _x.reg_motor_fb_rpm_right, _x.reg_flipper_fb_position_pot1, _x.reg_flipper_fb_position_pot2, _x.reg_motor_fb_current_left, _x.reg_motor_fb_current_right, _x.reg_motor_charger_state, _x.reg_power_a_current, _x.reg_power_b_current, _x.reg_motor_flipper_angle, _x.battery_current_a, _x.battery_current_b,) = _get_struct_11i2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11i2h().pack(_x.reg_pwr_total_current, _x.reg_motor_fb_rpm_left, _x.reg_motor_fb_rpm_right, _x.reg_flipper_fb_position_pot1, _x.reg_flipper_fb_position_pot2, _x.reg_motor_fb_current_left, _x.reg_motor_fb_current_right, _x.reg_motor_charger_state, _x.reg_power_a_current, _x.reg_power_b_current, _x.reg_motor_flipper_angle, _x.battery_current_a, _x.battery_current_b))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.reg_pwr_total_current, _x.reg_motor_fb_rpm_left, _x.reg_motor_fb_rpm_right, _x.reg_flipper_fb_position_pot1, _x.reg_flipper_fb_position_pot2, _x.reg_motor_fb_current_left, _x.reg_motor_fb_current_right, _x.reg_motor_charger_state, _x.reg_power_a_current, _x.reg_power_b_current, _x.reg_motor_flipper_angle, _x.battery_current_a, _x.battery_current_b,) = _get_struct_11i2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11i2h = None
def _get_struct_11i2h():
    global _struct_11i2h
    if _struct_11i2h is None:
        _struct_11i2h = struct.Struct("<11i2h")
    return _struct_11i2h
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
