# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rr_openrover_driver_msgs/SmartBatteryStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SmartBatteryStatus(genpy.Message):
  _md5sum = "a952a8feedea27cab4667095d349334c"
  _type = "rr_openrover_driver_msgs/SmartBatteryStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

bool over_charged_alarm
bool terminate_charge_alarm
bool over_temp_alarm
bool terminate_discharge_alarm
bool remaining_capacity_alarm
bool remaining_time_alarm

bool initialized
bool discharging
bool fully_charged
bool fully_discharged

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','over_charged_alarm','terminate_charge_alarm','over_temp_alarm','terminate_discharge_alarm','remaining_capacity_alarm','remaining_time_alarm','initialized','discharging','fully_charged','fully_discharged']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,over_charged_alarm,terminate_charge_alarm,over_temp_alarm,terminate_discharge_alarm,remaining_capacity_alarm,remaining_time_alarm,initialized,discharging,fully_charged,fully_discharged

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SmartBatteryStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.over_charged_alarm is None:
        self.over_charged_alarm = False
      if self.terminate_charge_alarm is None:
        self.terminate_charge_alarm = False
      if self.over_temp_alarm is None:
        self.over_temp_alarm = False
      if self.terminate_discharge_alarm is None:
        self.terminate_discharge_alarm = False
      if self.remaining_capacity_alarm is None:
        self.remaining_capacity_alarm = False
      if self.remaining_time_alarm is None:
        self.remaining_time_alarm = False
      if self.initialized is None:
        self.initialized = False
      if self.discharging is None:
        self.discharging = False
      if self.fully_charged is None:
        self.fully_charged = False
      if self.fully_discharged is None:
        self.fully_discharged = False
    else:
      self.header = std_msgs.msg.Header()
      self.over_charged_alarm = False
      self.terminate_charge_alarm = False
      self.over_temp_alarm = False
      self.terminate_discharge_alarm = False
      self.remaining_capacity_alarm = False
      self.remaining_time_alarm = False
      self.initialized = False
      self.discharging = False
      self.fully_charged = False
      self.fully_discharged = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10B().pack(_x.over_charged_alarm, _x.terminate_charge_alarm, _x.over_temp_alarm, _x.terminate_discharge_alarm, _x.remaining_capacity_alarm, _x.remaining_time_alarm, _x.initialized, _x.discharging, _x.fully_charged, _x.fully_discharged))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.over_charged_alarm, _x.terminate_charge_alarm, _x.over_temp_alarm, _x.terminate_discharge_alarm, _x.remaining_capacity_alarm, _x.remaining_time_alarm, _x.initialized, _x.discharging, _x.fully_charged, _x.fully_discharged,) = _get_struct_10B().unpack(str[start:end])
      self.over_charged_alarm = bool(self.over_charged_alarm)
      self.terminate_charge_alarm = bool(self.terminate_charge_alarm)
      self.over_temp_alarm = bool(self.over_temp_alarm)
      self.terminate_discharge_alarm = bool(self.terminate_discharge_alarm)
      self.remaining_capacity_alarm = bool(self.remaining_capacity_alarm)
      self.remaining_time_alarm = bool(self.remaining_time_alarm)
      self.initialized = bool(self.initialized)
      self.discharging = bool(self.discharging)
      self.fully_charged = bool(self.fully_charged)
      self.fully_discharged = bool(self.fully_discharged)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10B().pack(_x.over_charged_alarm, _x.terminate_charge_alarm, _x.over_temp_alarm, _x.terminate_discharge_alarm, _x.remaining_capacity_alarm, _x.remaining_time_alarm, _x.initialized, _x.discharging, _x.fully_charged, _x.fully_discharged))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.over_charged_alarm, _x.terminate_charge_alarm, _x.over_temp_alarm, _x.terminate_discharge_alarm, _x.remaining_capacity_alarm, _x.remaining_time_alarm, _x.initialized, _x.discharging, _x.fully_charged, _x.fully_discharged,) = _get_struct_10B().unpack(str[start:end])
      self.over_charged_alarm = bool(self.over_charged_alarm)
      self.terminate_charge_alarm = bool(self.terminate_charge_alarm)
      self.over_temp_alarm = bool(self.over_temp_alarm)
      self.terminate_discharge_alarm = bool(self.terminate_discharge_alarm)
      self.remaining_capacity_alarm = bool(self.remaining_capacity_alarm)
      self.remaining_time_alarm = bool(self.remaining_time_alarm)
      self.initialized = bool(self.initialized)
      self.discharging = bool(self.discharging)
      self.fully_charged = bool(self.fully_charged)
      self.fully_discharged = bool(self.fully_discharged)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10B = None
def _get_struct_10B():
    global _struct_10B
    if _struct_10B is None:
        _struct_10B = struct.Struct("<10B")
    return _struct_10B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
