// Generated by gencpp from file rr_openrover_driver_msgs/RawRrOpenroverDriverFastRateData.msg
// DO NOT EDIT!


#ifndef RR_OPENROVER_DRIVER_MSGS_MESSAGE_RAWRROPENROVERDRIVERFASTRATEDATA_H
#define RR_OPENROVER_DRIVER_MSGS_MESSAGE_RAWRROPENROVERDRIVERFASTRATEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rr_openrover_driver_msgs
{
template <class ContainerAllocator>
struct RawRrOpenroverDriverFastRateData_
{
  typedef RawRrOpenroverDriverFastRateData_<ContainerAllocator> Type;

  RawRrOpenroverDriverFastRateData_()
    : header()
    , left_motor(0)
    , right_motor(0)
    , flipper_motor(0)  {
    }
  RawRrOpenroverDriverFastRateData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_motor(0)
    , right_motor(0)
    , flipper_motor(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_motor_type;
  _left_motor_type left_motor;

   typedef int32_t _right_motor_type;
  _right_motor_type right_motor;

   typedef int32_t _flipper_motor_type;
  _flipper_motor_type flipper_motor;





  typedef boost::shared_ptr< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> const> ConstPtr;

}; // struct RawRrOpenroverDriverFastRateData_

typedef ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<std::allocator<void> > RawRrOpenroverDriverFastRateData;

typedef boost::shared_ptr< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData > RawRrOpenroverDriverFastRateDataPtr;
typedef boost::shared_ptr< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData const> RawRrOpenroverDriverFastRateDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator1> & lhs, const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_motor == rhs.left_motor &&
    lhs.right_motor == rhs.right_motor &&
    lhs.flipper_motor == rhs.flipper_motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator1> & lhs, const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rr_openrover_driver_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac325592ef354d083265d71820563c4b";
  }

  static const char* value(const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac325592ef354d08ULL;
  static const uint64_t static_value2 = 0x3265d71820563c4bULL;
};

template<class ContainerAllocator>
struct DataType< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rr_openrover_driver_msgs/RawRrOpenroverDriverFastRateData";
  }

  static const char* value(const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 left_motor\n"
"int32 right_motor\n"
"int32 flipper_motor\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_motor);
      stream.next(m.right_motor);
      stream.next(m.flipper_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawRrOpenroverDriverFastRateData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rr_openrover_driver_msgs::RawRrOpenroverDriverFastRateData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_motor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_motor);
    s << indent << "flipper_motor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flipper_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RR_OPENROVER_DRIVER_MSGS_MESSAGE_RAWRROPENROVERDRIVERFASTRATEDATA_H
