(cl:defpackage rr_openrover_driver_msgs-msg
  (:use )
  (:export
   "<RAWRROPENROVERDRIVERFASTRATEDATA>"
   "RAWRROPENROVERDRIVERFASTRATEDATA"
   "<RAWRROPENROVERDRIVERMEDRATEDATA>"
   "RAWRROPENROVERDRIVERMEDRATEDATA"
   "<RAWRROPENROVERDRIVERSLOWRATEDATA>"
   "RAWRROPENROVERDRIVERSLOWRATEDATA"
   "<SMARTBATTERYSTATUS>"
   "SMARTBATTERYSTATUS"
  ))

