(cl:in-package rr_openrover_driver_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          REG_MOTOR_FAULT_FLAG_LEFT-VAL
          REG_MOTOR_FAULT_FLAG_LEFT
          REG_MOTOR_TEMP_LEFT-VAL
          REG_MOTOR_TEMP_LEFT
          REG_MOTOR_TEMP_RIGHT-VAL
          REG_MOTOR_TEMP_RIGHT
          REG_POWER_BAT_VOLTAGE_A-VAL
          REG_POWER_BAT_VOLTAGE_A
          REG_POWER_BAT_VOLTAGE_B-VAL
          REG_POWER_BAT_VOLTAGE_B
          REG_ROBOT_REL_SOC_A-VAL
          REG_ROBOT_REL_SOC_A
          REG_ROBOT_REL_SOC_B-VAL
          REG_ROBOT_REL_SOC_B
          BATTERY_MODE_A-VAL
          BATTERY_MODE_A
          BATTERY_MODE_B-VAL
          BATTERY_MODE_B
          BATTERY_TEMP_A-VAL
          BATTERY_TEMP_A
          BATTERY_TEMP_B-VAL
          BATTERY_TEMP_B
          BATTERY_VOLTAGE_A-VAL
          BATTERY_VOLTAGE_A
          BATTERY_VOLTAGE_B-VAL
          BATTERY_VOLTAGE_B
          BUILDNO-VAL
          BUILDNO
))