(cl:in-package rr_openrover_driver_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          OVER_CHARGED_ALARM-VAL
          OVER_CHARGED_ALARM
          TERMINATE_CHARGE_ALARM-VAL
          TERMINATE_CHARGE_ALARM
          OVER_TEMP_ALARM-VAL
          OVER_TEMP_ALARM
          TERMINATE_DISCHARGE_ALARM-VAL
          TERMINATE_DISCHARGE_ALARM
          REMAINING_CAPACITY_ALARM-VAL
          REMAINING_CAPACITY_ALARM
          REMAINING_TIME_ALARM-VAL
          REMAINING_TIME_ALARM
          INITIALIZED-VAL
          INITIALIZED
          DISCHARGING-VAL
          DISCHARGING
          FULLY_CHARGED-VAL
          FULLY_CHARGED
          FULLY_DISCHARGED-VAL
          FULLY_DISCHARGED
))