// Generated by gencpp from file swiftnav_driver/gps_loc.msg
// DO NOT EDIT!


#ifndef SWIFTNAV_DRIVER_MESSAGE_GPS_LOC_H
#define SWIFTNAV_DRIVER_MESSAGE_GPS_LOC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace swiftnav_driver
{
template <class ContainerAllocator>
struct gps_loc_
{
  typedef gps_loc_<ContainerAllocator> Type;

  gps_loc_()
    : tow(0)
    , loc()  {
    }
  gps_loc_(const ContainerAllocator& _alloc)
    : tow(0)
    , loc(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _tow_type;
  _tow_type tow;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _loc_type;
  _loc_type loc;





  typedef boost::shared_ptr< ::swiftnav_driver::gps_loc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swiftnav_driver::gps_loc_<ContainerAllocator> const> ConstPtr;

}; // struct gps_loc_

typedef ::swiftnav_driver::gps_loc_<std::allocator<void> > gps_loc;

typedef boost::shared_ptr< ::swiftnav_driver::gps_loc > gps_locPtr;
typedef boost::shared_ptr< ::swiftnav_driver::gps_loc const> gps_locConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swiftnav_driver::gps_loc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swiftnav_driver::gps_loc_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swiftnav_driver::gps_loc_<ContainerAllocator1> & lhs, const ::swiftnav_driver::gps_loc_<ContainerAllocator2> & rhs)
{
  return lhs.tow == rhs.tow &&
    lhs.loc == rhs.loc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swiftnav_driver::gps_loc_<ContainerAllocator1> & lhs, const ::swiftnav_driver::gps_loc_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swiftnav_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swiftnav_driver::gps_loc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swiftnav_driver::gps_loc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swiftnav_driver::gps_loc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be07eed9e736cdda9531572e561caca9";
  }

  static const char* value(const ::swiftnav_driver::gps_loc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe07eed9e736cddaULL;
  static const uint64_t static_value2 = 0x9531572e561caca9ULL;
};

template<class ContainerAllocator>
struct DataType< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swiftnav_driver/gps_loc";
  }

  static const char* value(const ::swiftnav_driver::gps_loc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tow\n"
"geometry_msgs/Point loc\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swiftnav_driver::gps_loc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tow);
      stream.next(m.loc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_loc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swiftnav_driver::gps_loc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swiftnav_driver::gps_loc_<ContainerAllocator>& v)
  {
    s << indent << "tow: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "loc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.loc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWIFTNAV_DRIVER_MESSAGE_GPS_LOC_H
