// Generated by gencpp from file swiftnav_driver/imu_scaled.msg
// DO NOT EDIT!


#ifndef SWIFTNAV_DRIVER_MESSAGE_IMU_SCALED_H
#define SWIFTNAV_DRIVER_MESSAGE_IMU_SCALED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace swiftnav_driver
{
template <class ContainerAllocator>
struct imu_scaled_
{
  typedef imu_scaled_<ContainerAllocator> Type;

  imu_scaled_()
    : tow(0)
    , acc()
    , gyr()  {
    }
  imu_scaled_(const ContainerAllocator& _alloc)
    : tow(0)
    , acc(_alloc)
    , gyr(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _tow_type;
  _tow_type tow;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acc_type;
  _acc_type acc;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _gyr_type;
  _gyr_type gyr;





  typedef boost::shared_ptr< ::swiftnav_driver::imu_scaled_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swiftnav_driver::imu_scaled_<ContainerAllocator> const> ConstPtr;

}; // struct imu_scaled_

typedef ::swiftnav_driver::imu_scaled_<std::allocator<void> > imu_scaled;

typedef boost::shared_ptr< ::swiftnav_driver::imu_scaled > imu_scaledPtr;
typedef boost::shared_ptr< ::swiftnav_driver::imu_scaled const> imu_scaledConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swiftnav_driver::imu_scaled_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swiftnav_driver::imu_scaled_<ContainerAllocator1> & lhs, const ::swiftnav_driver::imu_scaled_<ContainerAllocator2> & rhs)
{
  return lhs.tow == rhs.tow &&
    lhs.acc == rhs.acc &&
    lhs.gyr == rhs.gyr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swiftnav_driver::imu_scaled_<ContainerAllocator1> & lhs, const ::swiftnav_driver::imu_scaled_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swiftnav_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swiftnav_driver::imu_scaled_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swiftnav_driver::imu_scaled_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swiftnav_driver::imu_scaled_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3bec1428d9809c2fe2f8b896685b9fc";
  }

  static const char* value(const ::swiftnav_driver::imu_scaled_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3bec1428d9809c2ULL;
  static const uint64_t static_value2 = 0xfe2f8b896685b9fcULL;
};

template<class ContainerAllocator>
struct DataType< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swiftnav_driver/imu_scaled";
  }

  static const char* value(const ::swiftnav_driver::imu_scaled_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tow\n"
"geometry_msgs/Vector3 acc\n"
"geometry_msgs/Vector3 gyr\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swiftnav_driver::imu_scaled_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tow);
      stream.next(m.acc);
      stream.next(m.gyr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_scaled_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swiftnav_driver::imu_scaled_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swiftnav_driver::imu_scaled_<ContainerAllocator>& v)
  {
    s << indent << "tow: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "acc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acc);
    s << indent << "gyr: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.gyr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWIFTNAV_DRIVER_MESSAGE_IMU_SCALED_H
