// Generated by gencpp from file swiftnav_driver/s16_Vec3.msg
// DO NOT EDIT!


#ifndef SWIFTNAV_DRIVER_MESSAGE_S16_VEC3_H
#define SWIFTNAV_DRIVER_MESSAGE_S16_VEC3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swiftnav_driver
{
template <class ContainerAllocator>
struct s16_Vec3_
{
  typedef s16_Vec3_<ContainerAllocator> Type;

  s16_Vec3_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  s16_Vec3_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> const> ConstPtr;

}; // struct s16_Vec3_

typedef ::swiftnav_driver::s16_Vec3_<std::allocator<void> > s16_Vec3;

typedef boost::shared_ptr< ::swiftnav_driver::s16_Vec3 > s16_Vec3Ptr;
typedef boost::shared_ptr< ::swiftnav_driver::s16_Vec3 const> s16_Vec3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swiftnav_driver::s16_Vec3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swiftnav_driver::s16_Vec3_<ContainerAllocator1> & lhs, const ::swiftnav_driver::s16_Vec3_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swiftnav_driver::s16_Vec3_<ContainerAllocator1> & lhs, const ::swiftnav_driver::s16_Vec3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swiftnav_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85729383565f7e059d4a213b3db1317b";
  }

  static const char* value(const ::swiftnav_driver::s16_Vec3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85729383565f7e05ULL;
  static const uint64_t static_value2 = 0x9d4a213b3db1317bULL;
};

template<class ContainerAllocator>
struct DataType< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swiftnav_driver/s16_Vec3";
  }

  static const char* value(const ::swiftnav_driver::s16_Vec3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n"
"int16 y\n"
"int16 z\n"
;
  }

  static const char* value(const ::swiftnav_driver::s16_Vec3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct s16_Vec3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swiftnav_driver::s16_Vec3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swiftnav_driver::s16_Vec3_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int16_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWIFTNAV_DRIVER_MESSAGE_S16_VEC3_H
